### ISSUE TITLE
Eclipse error: Execution of default goal... A required class was missing..

### ISSUE THREAD

**Issue by cptwunderlich** [highsource/maven-jaxb2-plugin#69] opened 2015-12-11 14:35 UTC
I have this error constantly marked on my pom.xml. It all works just fine from the command line.

Setup: 
Windows 10, Eclipse Mars 4.5.1 (Build 20150924-1200), M2e 1.6.2.20150902-0002, maven-jaxb2-plugin 0.13.1

Error:

```
Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate failed: A required class was missing while executing org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.13.1:generate: com/sun/xml/bind/api/ErrorListener
```

Stack trace:
https://gist.github.com/cptwunderlich/b088e8e5d6116084ba94

Edit 17.01.2017:
Still the same issue on latest Eclipse version:
  Version: Neon.1a Release (4.6.1)
  Build id: 20161007-1200

**Comment by highsource** [comment] 2015-12-12 19:37
Could you please share the log ia pastebin? Formatting is broken.

At the moment I honestly don't know how I can help. From my point of view, this must be Eclipse/M2E problem, any chance that you could file it there?

What I'd try to do is to compare classpaths when executing from the command line vs. via Eclipse.

**Comment by cptwunderlich** [comment] 2015-12-15 13:31
It's not broken, that's the way Eclipse displays it (so, yes, broken, but by design...)

Googling some more turned up this StackOverflow thread:
http://stackoverflow.com/questions/10387610/maven-jaxb2-xjc-plugin-m2e-plugin-execution-not-covered

Which is basically excaclty what can be found in the M2E Wiki:
http://www.eclipse.org/m2e/documentation/m2e-execution-not-covered.html#viewing-effective-lifecycle-mapping

And it does fix the problem!

What baffles me though, is the fact, that you actually have an `lifecycle-mapping-metadata.xml` 
For some reason, M2E still doesn't know which goal to execute.

**Comment by highsource** [comment] 2015-12-16 19:06
Apparently we had a similar problem before (#59).

As @efaille commented [here](https://github.com/highsource/maven-jaxb2-plugin/issues/59#issuecomment-141505606), he could solve the problem with the Eclispe setting from this answer:

http://stackoverflow.com/a/26413432/303810

So try to add -vm option to the eclipse.ini:

```
-vm
<PATH_TO_JDK>\jre\bin\javaw.exe
```

Do you see these messages somewhere?

```
[WARNING] The POM for org.glassfish.jaxb:jaxb-runtime:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.glassfish.jaxb:jaxb-xjc:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Error injecting: org.jvnet.mjiip.v_2.XJC2Mojo
```

If you do, that'd be a sign of this problem.

**Comment by cptwunderlich** [comment] 2015-12-17 09:41
I don't see those messages.

Setting the option in eclipse.ini fails and it shows me a dialog with the options set. Somewhere else the -vm option is already set and points to `C:\ProgramData\Oracle\Java\javapath\javaw.exe` which is a link to ``C:\Program Files\Java\jre1.8.0_66\bin\javaw.exe`

**Comment by cptwunderlich** [comment] 2016-01-26 10:06
I still have the same issue, but with a slightly different error message. Now it can't find com/sun/codemodel/CodeWriter

https://gist.github.com/cptwunderlich/83d78c9ff6797c466413

Does no one else have this error? I'm not doing anything exotic here. My config:

        <plugin>
          <groupId>org.jvnet.jaxb2.maven2</groupId>
          <artifactId>maven-jaxb2-plugin</artifactId>
          <version>${version.jaxb2.plugin}</version>
          <executions>
            <execution>
              <goals>
                <goal>generate</goal>
              </goals>
            </execution>
          </executions>
        </plugin>

**Comment by thomas-brand** [comment] 2016-01-29 04:20
Hi, I have exactly the same problem. Regards. Thomas

**Comment by highsource** [comment] 2016-01-29 06:58
Which exact Eclipse version do you use?

**Comment by thomas-brand** [comment] 2016-01-29 07:58
Mars.1 (4.5.1) Build id: 20150924-1200
Am 29.01.2016 07:58 schrieb "Alexey Valikov" <notifications@github.com>:

**Comment by jaoh** [comment] 2016-02-03 16:03
Version: Mars.1 Release (4.5.1)
Build id: 20150924-1200

I can confirm this

**Comment by jaoh** [comment] 2016-02-03 16:14
Are there any versions of Eclipse which work better ?

**Comment by birlibirloque** [comment] 2016-03-11 19:55
With this version works like a charm
Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600

**Comment by highsource** [comment] 2016-03-12 16:46
Closing as (a) works in the reported version (b) there's nothing I can do on the plugin side.

**Comment by ChrissW-R1** [comment] 2016-04-28 20:25
This error still occurs in my enviroment. Up to version 0.12.1 it works fine, but since 0.13 I'll get this error. New fresh and clean installation of eclipse and the plugins doesn't help.

Enviroment:
eclipse | Mars.2 Release (4.5.2) | Build id: 20160218-0600
M2E - Maven Integration for Eclipse | 16.2.20150902-0002

It was also already reported as a bug in the eclipse / m2e bugtracker: https://bugs.eclipse.org/bugs/show_bug.cgi?id=486547

**Comment by hheg** [comment] 2016-05-05 09:24
@ChrissW-R1 Are you sure its not related to the wrong VM used? I had the exact same stacktrace. Check [this](http://diggingthroughcode.blogspot.se/2016/05/trouble-with-maven-jaxb2-plugin-and.html) post out and it may help you fixing/verifying it.

**Comment by darrenreimer** [comment] 2016-06-08 13:49
I resolved this issue by removing any JREs from my Eclipse preferences (Java > Installed JREs) and only leaving the selected JDK there.  Even though the JREs were not selected, they still cause the issue and have to be removed.  I was able to leave the JREs on my system.

**Comment by darrenreimer** [comment] 2016-08-15 20:57
Another coworker just ran into this and for him it seemed the critical factor was which Java was being used to run Eclipse.  It won't use what JAVA_HOME is configured too, but the first Java runtime available.  He removed all jres from his system and only left a jdk and that resolved the issue.

**Comment by buko** [comment] 2016-10-30 12:57
I'll just add a quick comment here on what I've found.

1. This issue isn't fixed. The only work around to to use version 0.12.1 of this plugin.
2. The problem is definitely related to Eclipse. Not a problem with the plugin itself.
3. Removing all Installed JREs from Eclipse doesn't solve the problem.

To actually fix this problem **you must use a JDK to launch Eclipse**. I repeat, what matter is whether you use a JDK or a JRE to launch Eclipse not the 'Installed JREs'. This plugin does not work inside Eclipse unless a JDK is used to launch Eclipse.

To fix this issue you must:

1. Open up 'eclipse.ini' and change the VM like so:
`-vm
C:\data\applications\Java\jdk1.8.0_91\bin`

BTW, @highsource , this plugin rocks! Very impressed with how robust this plugin is and its ability to support large-scale schema-first development. Keep up the good work!

**Comment by russellhoff** [comment] 2016-12-16 12:27
I've got the same issue.

**Comment by javarules** [comment] 2017-01-07 13:46
Same issue with the latest version of Spring Tool Suite (base on Eclipse 4.6). VM parameter didn't help - had to revert to 0.12.1 version of the plugin.

**Comment by highsource** [comment] 2017-01-11 07:36
Hm... Seems like I really have to repackage XJC to fix this.

**Comment by JSamir** [comment] 2017-02-27 17:31
I have the same issue, only version 0.12.1 of the plugin helps.

**Comment by highsource** [comment] 2017-03-07 08:00
I'm reopening this since it does not seem to get fixed from the Eclipse side.

**Comment by highsource** [comment] 2017-03-07 12:24
@cptwunderlich
@thomas-brand 
@jaoh 
@birlibirloque 
@ChrissW-R1 
@darrenreimer 
@buko 
@russellhoff 
@javarules 
@JSamir 

Please try 0.13.2. I've added all the dependencies of `jaxb-runtime` and `jaxb-xjc` directly to `maven-jaxb2-plugin` and `maven-jaxb22-plugin`. Eclipse still complains that:

```
3/7/17, 10:49:05 AM GMT+1: [WARN] The POM for org.glassfish.jaxb:jaxb-runtime:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for org.glassfish.jaxb:jaxb-runtime:2.2.11
```

But since all the dependencies are immediately available in the `maven-jaxb2-plugin` itself, it should not matter much.

This seems to work in Eclipse, tried in a virgin Neon 2:

![issue-69](https://cloud.githubusercontent.com/assets/6707996/23656206/fed02686-0338-11e7-9c94-25842f8da88c.gif)

Please try it out and let me know.

**Comment by highsource** [comment] 2017-03-07 12:25
I'll keep it open until confirmation.

**Comment by remillet** [comment] 2017-03-14 23:59
FYI, "buko's" comment above on Oct 30, 2016 helped resolve this issue for me.

**Comment by n-pac** [comment] 2017-03-27 10:30
0.13.2 does the trick here on a brand new Neon.3 (20170314-1500), while still seeing glassfish dependencies warnings.

**Comment by highsource** [comment] 2017-03-28 11:52
Dependency warning won't go away. That's a problem between Maven, Eclipse and JAXB POMs. And it's something I don't really want to solve.

**Comment by highsource** [comment] 2017-03-28 11:52
Closing as it seems to be fixed now.

**Closed by highsource** 2017-03-28 11:52 UTC
Labels: bug, wontfix

**Comment by walhow** [comment] 2020-04-10 16:15
If you are still having this issue, make sure your Eclipse is building with a JDK, not JRE. Setting the .ini file might not be enough, you need to check Build properties.

**Comment by topEngineerRay** [comment] 2020-12-01 10:26
i am using the version 0.12.3, and i got the same error today. I am using the intelij
