### ISSUE TITLE
episode dependencies are getting re-generated and incomplete jaxb classes 

### ISSUE THREAD

**Issue by wallmarc** [highsource/maven-jaxb2-plugin#60] opened 2015-09-23 19:11 UTC
Hi,
I have some problems with episode dependencies in that dependent modules are getting their schemas re-compiled, and what worse is, the resulting jaxb-classes are incomplete. This greatly prevents modularisation of schema components.

As an example I took https://github.com/highsource/maven-jaxb2-plugin/tree/master/samples/episode and just modified slightly to make it possible to build standalone from the rest of the product. I locked down the versions to:
        jaxb.version=2.2.11
        maven.jaxb2.plugin.version=0.13.0

When listing the generated contents of the "a" module, I can see that the original build of "a" contains lots more classes than the "a"-classes generated by the "b" build.

$ ls -la /cygdrive/c/proj/maven-jaxb2-plugin-master/samples/episode/a/target/generated-sources/xjc/a/
total 21
drwxrwx---+ 1 Administrators Domain Users    0 Sep 23 20:37 .
drwxrwx---+ 1 Administrators Domain Users    0 Sep 23 20:37 ..
-rwxrwx---+ 1 Administrators Domain Users 1749 Sep 23 20:37 A1Type.java
-rwxrwx---+ 1 Administrators Domain Users 1173 Sep 23 20:37 A2EnumType.java
-rwxrwx---+ 1 Administrators Domain Users 1705 Sep 23 20:37 AType.java
-rwxrwx---+ 1 Administrators Domain Users 1979 Sep 23 20:37 ObjectFactory.java
-rwxrwx---+ 1 Administrators Domain Users  478 Sep 23 20:37 package-info.java

$ ls -la /cygdrive/c/proj/maven-jaxb2-plugin-master/samples/episode/b/target/generated-sources/xjc/a
total 8
drwxrwx---+ 1 Administrators Domain Users    0 Sep 23 20:37 .
drwxrwx---+ 1 Administrators Domain Users    0 Sep 23 20:37 ..
-rwxrwx---+ 1 Administrators Domain Users 1190 Sep 23 20:37 A2EnumType.java
-rwxrwx---+ 1 Administrators Domain Users 1202 Sep 23 20:37 ObjectFactory.java

My environment:
>echo %JAVA_HOME%
C:\Progra~1\Java\jdk1.7.0_21

>mvn -version
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T18:37:52+01:00)
Maven home: C:\tools\apache-maven-3.2.1
Java version: 1.7.0_21, vendor: New Oracle
Java home: C:\Progra~1\Java\jdk1.7.0_21\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

The behavior for me right now is that I can't use a.ObjectFactory (in classpath of "b") as it is incomplete.

I would preferrably not re-generate the a.ObjectFactory (and releated classes) at all.
Alternatively, if they are being re-generated they should be identical as the original compile from a-module.

Can you suggest a way to workaround this, if one exists?

Best Regards
Marcus Wallin

**Comment by highsource** [comment] 2015-09-24 07:48
Hi,

this is a problem in XJC, we can't do much about it in the plugin.

The problem is that even if you use episodes, XJC sometimes still decides to generate things anew. I've had this behaviour with enums (like you report) and also sometimes with `ObjectFactory`. Enums normally work since the latest version, if you're getting an enum generated then you probably use a different typesafe enum base. Normally you've got things generated if they are not already mapped in episodes. But XJC sometimes generates things even if they're mapped, this is an issue in XJC.

Fortunately, the workaround is quite simple. Just delete unnecessary packages in a post-process script. I do this with the `delete` task of the `maven-antrun-plugin`:

https://github.com/highsource/ogc-schemas/blob/master/citygml/2.0/pom.xml#L85-L87

I agree that this is not so pretty, but it works very well. The [ogc-schemas](https://github.com/highsource/ogc-schemas) project I mention above is a huge schema compilation project, and it is fully modularized - you get a few dozens of individual JARs per specification/schema/version.

Hope this helps.

Best wishes,
Alexey

**Comment by highsource** [comment] 2015-10-31 10:25
Closing as the question seems to be answered.

**Closed by highsource** 2015-10-31 10:25 UTC
Labels: question
