### ISSUE TITLE
Add ability to define endorsed dirs in order to select specific JAXB implementations 

### ISSUE THREAD

**Issue by himslm01** [highsource/maven-jaxb2-plugin#34] opened 2015-01-11 10:28 UTC
Other plugin artifacts, for instance maven-compiler-plugin, allow arguments to be added which set the compiler's endorsed dirs.

<endorseddirs>${endorsed.dir}</endorseddirs>

That allows one build machine using one JRE to switch which JAXB implementation to use.

I would like to do similar in maven-jaxb2-plugin.

I tried:
                <args>
                  <arg>-Djava.endorsed.dirs=${endorsed.dir}</arg>
                </args>

but the JAXB API is still loaded from the system's Java and not from the ${endorsed.dir}

[INFO] Started execution.
[INFO] JAXB API is loaded from the [jar:file:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Classes/classes.jar!].
[INFO] Detected JAXB API version [2.1].

**Comment by highsource** [comment] 2015-01-13 09:22
This is a nice idea. I'm just not sure if this can be implemented without big effort.

The problem is that right now XJC is invoked in the same process, not in a separate process. In this structure it is not possible to change the endorsed dirs (as it is an already running process).

So in order to set the endorsed dirs I'd have to invoke XJC in a separate process/VM. But in this case it won't have any connection to the current Maven context. So most of the things like using resources from Maven artifacts etc. won't work anymore. An these are important features.

To make it work I'd need to implement something like "XJC bundled with Maven invokable via CLI". Which is not impossible but quite an effort.

Please tell me a bit more about your use case. You can add JAXB API to the endorsed dirs or set the endorsed dirs system-wide. These are probably options you've already considered, why aren't they suitable?

**Comment by bertramn** [comment] 2015-01-17 14:46
Hi Mark,

Not sure I understand your exact requirements but I am using the maven-jaxb22-plugin and specify the extact JAXB implementation that needs to be used. There are a few things you need to set up but it will work as if you prepare your JDKs endorsed folders. An area where people usually make an error is when creating the endorsed directory just make sure you only put the jaxb-api of the version you are after into the endorsed folder.

 Below is what works for me:

1. prepare an endorsed folder

As mentioned, only put the jaxb-api jar into the endorsed folder, the jaxb-runtime just has to be added as a normal project dependency. The jaxb-xjc goes into the maven-jaxb22-plugin configuation.

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-dependency-plugin</artifactId>
    <executions>
        <execution>
            <id>setup-endorsed</id>
            <phase>validate</phase>
            <goals>
                <goal>copy</goal>
            </goals>
            <configuration>
                <artifactItems>
                    <artifactItem>
                        <groupId>javax.xml.bind</groupId>
                        <artifactId>jaxb-api</artifactId>
                        <version>2.2.11.patched</version>
                    </artifactItem>
                </artifactItems>
                <outputDirectory>${project.build.directory}/endorsed</outputDirectory>
            </configuration>
        </execution>
    </executions>
</plugin>
```

2. configure your compiler plugin

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.1</version>
    <configuration>
        <source>1.7</source>
        <target>1.7</target>
        <compilerArguments>
            <endorseddirs>${project.build.directory}/endorsed</endorseddirs>
        </compilerArguments>
    </configuration>
</plugin>
```

3. configure surefire for testing

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <configuration>
        <forkCount>1</forkCount>
        <reuseForks>true</reuseForks>
        <systemProperties>
            <property>
                <name>java.endorsed.dirs</name>
                <value>${project.build.directory}/endorsed</value>
            </property>
        </systemProperties>
    </configuration>
</plugin>
```

4. configure your maven-jaxb2-plugin to know about the JAXB runtime and xjc compiler you want to use

```xml
<plugin>
    <groupId>org.jvnet.jaxb2.maven2</groupId>
    <artifactId>maven-jaxb22-plugin</artifactId>
    <version>0.12.3</version>
    <executions>
        <execution>
            <id>generate-core-types</id>
            <phase>generate-sources</phase>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <plugins>
                    <plugin>
                        <groupId>org.jvnet.jaxb2_commons</groupId>
                        <artifactId>jaxb2-basics</artifactId>
                    </plugin>
                </plugins>
                <extension>true</extension>
                <args>
                    <arg>-Xannotate</arg>
                </args>
            </configuration>
        </execution>
    </executions>
    <dependencies>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>2.2.11.patched</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-xjc</artifactId>
            <version>2.2.11.patched</version>
        </dependency>
    </dependencies>
</plugin>
```

When I run this setup, I get classes that are generated by the `2.2.11-patched` XJC compiler I specified in the setup.

```java
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) 
/// Reference Implementation, v2.2.11.patched 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.17 at 11:52:13 PM EST 
//

package com.bla;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Amount", propOrder = { "value" })
public class Amount {
}
```

The only thing I never tried is if I can go back and use 2.1 JAXB setup. But in theory it should work in the same way as this above method worked for me from 2.2.4 all the way to 2.2.11.

Hope this helps,
Niels

**Comment by himslm01** [comment] 2015-01-20 22:07
Hi Alexey - apologies for not responding sooner,

> Please tell me a bit more about your use case

The software development team I work in has one Jenjins build server. We do all our building for various products on that one server. Some products are tested and qualified to use jaxb2.0, some jaxb2.1 and some jaxb2.2.

We we all know, I can compile against the three different versions by using the endorseddirs compilerArguments of the maven-compiler-plugin.

What Niels said is that I can also switch between the JAXB XJC implementation using dependencies of the maven-jaxb22-plugin. I had not realised that - so I'll go and test it and get back to you.

Thanks for the comments.

**Comment by highsource** [comment] 2015-01-21 07:37
@himslm01 

`endorsed` is only relevant to the version of the JAXB **API** you're using. If you have an older JDK with 2.1 but need 2.2, then you'd put jaxb-api 2.2 in some dir and make it endorsed.

If you just need to compile for `2.0`, `2.1` and `2.2` then use `maven-jaxb20-plugin`, `maven-jaxb21-plugin`, `maven-jaxb22-plugin`. These variants are built with the appropriate version of JAXB XJC (schema compiler). For instance 2.1:

https://github.com/highsource/maven-jaxb2-plugin/blob/master/plugin-2.1/pom.xml#L23-L33

So you're guaranteed that exacthly the "right" version of JAXB-XJC will be used. So you actually don't need to reconfigure dependencies of the plugin, just use the appropriate `maven-jaxb2x-plugin` version.

But as I noted above, this advise only addresses schema compilation. In the runtime you'll need to test in prepared environments. But the runtime is out of the scope of this Maven plugin.

Please let me know if this solves your case.

**Comment by himslm01** [comment] 2015-01-21 20:33
Hi. Thanks for your reply.

Thank you - I think I'm following you now.

Can I confirm my understanding: your are saying that when I am converting XSD to Java source code in the generate-sources phase with maven-jaxb2x-plugin I can ignore the info line:

[INFO] Detected JAXB API version [2.1].

When I compile the Java source code to bytecode in the compile phase with maven-compiler-plugin I will use the endorseddirs compiler argument to give the compiler the right JAXB2 API to compile against.

**Comment by highsource** [comment] 2015-01-21 20:42
Yes and no, not entirely.

No - you can't ignore it. The JAXB API classes are used by the schema compiler (XJC). So if you'll try to compile with target 2.2 on an older JDK, you'll likely run into problems that some annotation field could not be found,

But JAXB API are backwards-compatible. So if you have a JDK with JAXB API 2.2 (either actual JDK or JAXB API in an endorsed directory), then you'll be able to compile with JAXB API 2.0, 2.1 and 2.2 targets.

So I'd recommend updating your compile-time JDK to JAXB API 2.2 in any case.

Not sure it answers your question fully, feel free to ask if anything's unclear.

Best wishes,
Alexey

**Comment by himslm01** [comment] 2015-01-21 21:54
Hi Alexey,

Thanks for replying again.

Good, I'm glad you said all that because I thought I'd been misunderstanding something in the thread. 

So Niels' answer about using dependencies on maven-jaxb2x-plugin will not help me get, for instance, JAXB2.2 API available on a Java 6 build server.

I understand the backwards compatibility of JAXB, but as you say, I'm still going to need to ensure the JDK is new enough or put the JAXB API in an endorsed directory.

I return to my original pont in my first post, it is a great shame I cannot define the endorsed directory for the  maven-jaxb2x-plugin that from within the Maven pom. So my pom is not in control. I have to ensure developers / admins use the right JRE. I thought that the pom. My pom is not "the one-stop-shop for all things concerning the project". Which is a shame.

**Comment by highsource** [comment] 2015-01-22 07:02
Hi,

> So Niels' answer about using dependencies on maven-jaxb2x-plugin will not help me get, for instance, JAXB2.2 API available on a Java 6 build server.

> I understand the backwards compatibility of JAXB, but as you say, I'm still going to need to ensure the JDK is new enough or put the JAXB API in an endorsed directory.

Correct, your JAXB API in the compile JDK must be >= target JAXB API.

What I don't quite get is - why is it an issue for you? Updating JDK should not be a big deal, should it?

> I return to my original pont in my first post, it is a great shame I cannot define the endorsed directory for the maven-jaxb2x-plugin that from within the Maven pom. So my pom is not in control. I have to ensure developers / admins use the right JRE. I thought that the pom. My pom is not "the one-stop-shop for all things concerning the project". Which is a shame.

I do agree that this would have been more convenient, but I am not quite sure if this is the right thing to do.

First of all, there are technical issues with configuring the endorsed directory. Many Maven plugins just call some Java tool on the command line. In this case it's quite easy to pass additional CLI parameters to the new process (I think this is how it is handled in `maven-compiler-plugin`).

But `maven-jaxb2-plugin` is not quite an "average Maven plugin", it goes great length to allow advanced integration of schema compilation with the Maven stack (for instance loading schemas from Maven artifacts). This requires that the Maven stack is present in the compile time.

If we'd start XJC in a separate process (which is what would be required to do the endorsed thing), then this effectively cuts XJC from the Maven runtime in which the `maven-jaxb2-plugin` is executed. So either we'd lose all the Maven integration features OR we'd have to implement starting the Maven runtime (more or less identical to the original runtime) from within than new process. Which is a lot of effort (emedding Maven in XJC, passing the whole configuration etc.). Huge effort.

From the other hand the whole problem is actually to run the `maven-jaxb2-plugin` in an older JDK without updating it. This is a problem of environment management which is, from my point of view is out of the scope of Maven as a whole. If you'd want to do a 1.6 target compilation on an 1.5 JDK you wouldn't expect Maven to manage 1.5->1.6 for you, right?

You are right, POM should be a one-stop shop for everything project-related. But I'd argue that this implies certain prerequisites (like JDK or Maven version) which you have to provide. As we're talking a `javax`-API here, this is a part of JDK and has to be managed there. I'm not a big fan of how it is done but this is how it is done in Java, sorry. (The `maven-jaxb2-plugin` should check the JAXB API as prerequisite and fail if the expected version does not match, I'll file an issue for that.)

The feature you're proposing is not impossible, but:
* it is very effort-intensive,
* technically risky,
* workarounds a problem on the JDK/environment level, which I believe to be out of the scope, not just of `maven-jaxb2-plugin` but Maven altogether.

So I'm afraid this balance goes more in "won't fix" direction. I hope you can follow my arguments.

Best wishes,
Alexey.

**Comment by himslm01** [comment] 2015-01-22 11:33
Hi Alexey,

I completely understand your position.

A response of won't fix, especially with your excellent reasoning, is always a perfectly fine response to an enhancement request.

I'm glad we knocked the ideas about and had an intellectual discussion about the pros and cons. Thank you.

**Comment by bertramn** [comment] 2015-01-22 12:17
Hi Mark,

I can't see the point for an endorsed folder either but maybe I don't quite understand what you are trying to achieve. If you just want to generate a schema to different JAXB target versions, why not use a set of profiles to setup your target JAXB maven plugin and then use the profile activation mechanism in Jenkins.

Running the risk of failing the point, but maybe just have a look at this example and tell me if it does or does not do what you are trying to achieve:

https://github.com/bertramn/jaxb-multi-version

Also the earlier example I gave was making the point that even if the maven-jaxb22-plugin has a default preference for a JAXB version, you can still override this and plug whatever version you want in there (assuming you stay within the bounds of the 2 first release digits).

I found the plugin to work quite well and use it to build dependent libraries of schema artifacts with all sorts of bells and whistles. There are a few nasty bugs out there but they are mainly in the XSOM library, JAXB scd etc. and not really the plugins fault.

Take care,
Niels

**Comment by highsource** [comment] 2015-01-22 14:36
Closing with won't fix. Check for prerequisites will be contonued in #38.

**Closed by highsource** 2015-01-22 14:36 UTC
Labels: question
