### ISSUE TITLE
JAXB/Maven issue

### ISSUE THREAD

**Issue by divanmostert** [highsource/maven-jaxb2-plugin#159] opened 2018-09-21 12:28 UTC
Hi All,

I have a strange issue and not sure if it's a bug in maven-jaxb2-plugin, so just want to run this past you.

We have a product that stores application files as XML. We then have a Maven plugin, which loads these up and generate code from it.

Problem is that with Java 9 it only loads the root element when unmarshalling. Under Java 8, everything works perfectly fine.

I have a trimmed down version that illustrates the problem - see attached.
[Archive.zip](https://github.com/highsource/maven-jaxb2-plugin/files/2405290/Archive.zip)

The components are:
schemas: the JAXB generated code from the xsd
core: The "product" code doing the unmarshalling
mavenPlugin: A Maven plugin making use of the core code built above
useMaven: Making use of the Maven plugin built above

Thanks in advance.

Divan

**Comment by highsource** [comment] 2018-09-21 17:37
Your schema-derived classes are generated fine so this is not a bug in `maven-jaxb2-plugin`.

Closing the issue as it is out of the scope.

**Closed by highsource** 2018-09-21 17:37 UTC

**Comment by highsource** [comment] 2018-09-21 20:02
I've tried to check your code and found it quite difficult. It is definitely not an MCVE, there's a lot of stuff happening apart from unmarshalling so it's quite hard to say, what's actually going wrong.

The difference between Java 8 and Java 9 might point to problems which are due to the new module system. I don't have deep knowledge on it so I can't give any good hints. But maybe the package you load `JAXBContext` for is not exported correctly? Something in that direction.

I have also noted that you swallow exceptions with `catch (Exception e) {e.printStackTrace();}`. Probably better not do it.

My approach to debuging this would be to run Maven in debug mode and attach my IDE to Maven process using remote debugging. Then I'd tried analyzing the created `JAXBContext` and also step-by-step trace how the model is populated.

**Comment by divanmostert** [comment] 2018-09-24 06:05
Many thanks - appreciate your efforts.

**Comment by divanmostert** [comment] 2018-09-24 12:58
FYI: I've located the problem. Java 9 does not load the package level Annotations, thus the namespace info is lost

**Comment by divanmostert** [comment] 2018-09-24 14:43
Same problem as described here: https://stackoverflow.com/questions/52157040/jaxb-package-info-ignored-when-using-java-10#

**Comment by highsource** [comment] 2018-09-24 16:21
Cool that you've found that out. Seems like I had the same problem in `maven-jaxb2-plugin`, fixed in 0.14.0.
